[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
NIXPACKS_NPM_INSTALL_CMD = "npm install"
NIXPACKS_NPM_CI_CMD = "npm install"
CI = "false"
PUBLIC_URL = "."
REACT_APP_API_URL = "https://visort-defense-production.up.railway.app"
