[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "cd visort-last/backend && npm install",
  "cd visort-last/frontend && npm install"
]

[phases.build]
cmds = [
  "cd visort-last/frontend && npm run build"
]

[start]
cmd = "cd visort-last/backend && npm start"
