[build]
builder = "nixpacks"

[deploy]
startCommand = "cd visort-last/backend && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "$PORT"